version: '3.1'

services:

  db:
    image: mysql
    container_name: db
    restart: always
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dike2361
    volumes:
      - ~/Desktop/GDD/DSTP:/var/lib/mysql

  phpmyadmin:
    depends_on: [db]
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  tp-app:
    depends_on: [db]
    image: dstp-back-i
    container_name: tp-app
    restart: always
    ports:
      - "9000:9000"
    links:
      - db